const employeeActionTypes = {
    FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
    FETCH_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAILURE: 'GET_EMPLOYEES_FAILURE',
    SELECT_EMPLOYEE_UPDATE: 'SELECT_EMPLOYEE_UPDATE'
}

export default employeeActionTypes